FROM python:3.11-slim

# Prevents python from creating ".pyc" files when importing modules and make sure that your prints also show up in the docker logs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Sets up working directory inside of the container
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Installs... well, more dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .