name: "project-epiclock"

services:
  postgres_vector:
    image: pgvector/pgvector:pg17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${ENV_USER}
      POSTGRES_PASSWORD: ${ENV_PASSWORD}
      POSTGRES_DB: ${ENV_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  synthea_generator:
    build:
      context: .
      dockerfile: Dockerfile.synthea
    volumes:
      - ./data:/output

  epiclock_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      postgres_vector:
        condition: service_started
      synthea_generator:
        condition: service_completed_successfully
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENV_USER=${ENV_USER}
      - ENV_PASSWORD=${ENV_PASSWORD}
      - ENV_DATABASE=${ENV_DATABASE}
    volumes:
      - .:/app
    command: sleep infinity

volumes:
  postgres_data: