FROM eclipse-temurin:17-jdk-jammy
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/synthetichealth/synthea.git /synthea
WORKDIR /synthea
RUN ./gradlew build

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]