FROM python:3.11-slim

# Prevents python from creating ".pyc" files when importing modules and make sure that your prints also show up in the docker logs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Sets up working directory inside of the container
WORKDIR /app

# Install dependencies + Java JRE (required for Nextflow)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    git \
    curl \
    gcc \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -s https://get.nextflow.io | bash && \
    mv nextflow /usr/local/bin/ && \
    chmod +x /usr/local/bin/nextflow

# Install... well, more dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .