name: "project-epiclock"

services:
  postgres_vector:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${ENV_USER}
      POSTGRES_PASSWORD: ${ENV_PASSWORD}
      POSTGRES_DB: ${ENV_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  synthea_generator:
    profiles: ["tools"]
    build:
      context: .
      dockerfile: Dockerfile.synthea
    volumes:
      - ./data:/output
    command: -p 100 --exporter.csv.export=true --exporter.baseDirectory=/output

  epiclock_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - postgres_vector
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENV_USER=${ENV_USER}
      - ENV_PASSWORD=${ENV_PASSWORD}
      - ENV_DATABASE=${ENV_DATABASE}
    volumes:
      - .:/app
    command: sleep infinity

volumes:
  postgres_data: